#ifndef __VGE_GUI__
#define __VGE_GUI__

/**
@file
Subclass of GUI, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing GUI */
class VGE_GUI : public GUI
{
	protected:
		// Handlers for GUI events.
		void onFileLoad( wxCommandEvent& event );
		void onFileSave( wxCommandEvent& event );
		void onColourPickerChange( wxColourPickerEvent& event );
		void onLineClick( wxCommandEvent& event );
		void onBezierClick( wxCommandEvent& event );
		void onCircleClick( wxCommandEvent& event );
		void onRectClick( wxCommandEvent& event );
		void onPolygonClick( wxCommandEvent& event );
		void onInscPolyClick( wxCommandEvent& event );
	public:
		/** Constructor */
		VGE_GUI( wxWindow* parent );
	//// end generated class members


};

#endif // __VGE_GUI__
